version: "3"

volumes:
  es-data:
    driver: local

services:

  nginx:
    image: nginx:1.19
    restart: always
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PUBLIC_DATA_DIR}:/download/:ro

  fe:
    image: docker.gitlab.gwdg.de/ibb/ibb-fe:1.3.2
    restart: always
    environment:
      - NUXT_PUBLIC_APIS_BASE_URL=${PUBLIC_SERVER}/ibb/api

  jbrowse2:
    image: docker.gitlab.gwdg.de/ibb/api/ibb-jbrowse2:latest
    restart: always

  ontoscope:
    image: docker.gitlab.gwdg.de/ibb/api/ibb-ontoscope:latest
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      - BASE_URL=/ibb/swagger-ui
      - "URLS=[
        { url: '$PUBLIC_SERVER/ibb/api/geneservice/v1/q/openapi/', name: 'Gene Service' },
        { url: '$PUBLIC_SERVER/ibb/api/ontologyservice/v1/q/openapi/', name: 'Ontology Service' }
        ]" 

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    restart: always
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 0.5g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200 # should be disabled in production
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "curl -s localhost:9200 | grep -q 'You Know, for Search'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  geneservice:
    image: docker.gitlab.gwdg.de/ibb/api/geneservice:1.3.1
    restart: always
    depends_on:
      es:
        condition: service_healthy
    volumes:
      - ${PRIVATE_DATA_DIR}/geneservice:/data:ro
    environment:
      - MP_OPENAPI_SERVERS=$PUBLIC_SERVER/ibb/api/geneservice/v1/

  ontologyservice:
    image: docker.gitlab.gwdg.de/ibb/api/ontologyservice:1.3.0
    restart: always
    depends_on:
      es:
        condition: service_healthy
    environment:
      - MP_OPENAPI_SERVERS=$PUBLIC_SERVER/ibb/api/ontologyservice/v1/

  imageservice:
    image: docker.gitlab.gwdg.de/ibb/api/imageservice:1.5.0
    restart: always
    user: "${UID}:${GID}"
    depends_on:
      es:
        condition: service_healthy
    volumes:
      - ${IMAGE_DIR}:/images
         
  phenotypeservice:
    image: docker.gitlab.gwdg.de/ibb/api/phenotypeservice:1.5.0
    restart: always
    depends_on:
      es:
        condition: service_healthy
      imageservice:
        condition: service_started

  goannotationservice:
    image: docker.gitlab.gwdg.de/ibb/api/geneontologyservice:1.3.0
    restart: always
    depends_on:
      es:
        condition: service_healthy

  publicationservice:
    image: docker.gitlab.gwdg.de/ibb/api/ibb-publication:1.3.0
    restart: always
    depends_on:
      es:
        condition: service_healthy

  iblethalityservice:
    image: docker.gitlab.gwdg.de/ibb/api/lethalityservice:latest
    restart: always
    environment:
      - MP_OPENAPI_SERVERS=$PUBLIC_SERVER/ibb/api/iblethalityservice/v1/
      - QUARKUS_ELASTICSEARCH_HOSTS=es:9200
      - QUARKUS_HTTP_CORS=true

  querypipelineservice:
    image: docker.gitlab.gwdg.de/ibb/api/query-pipeline:1.3.0
    restart: always
    environment:
      - PUBLIC_SERVER=$PUBLIC_SERVER/ibb/api/querypipelineservice/v1/

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: "start-dev"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    profiles:
      - experimental
