events {
}

http {
  server {

    # This is the internal docker dns server, cache for 30 seconds
    resolver 127.0.0.11 valid=30s;

    location / {
      # Using the variable trick, nginx will now start even if the upstream host is not yet reachable.
      # Inside docker, need the resolver to work.
      set $upstream http://fe:8080;
      proxy_pass $upstream;
    }
    location /ibb/api/ontologyservice {
      set $upstream http://ontologyservice:8080;
      proxy_pass $upstream;
      rewrite ^/ibb/api/ontologyservice/v1/(.*)$ /$1 break;
    }
    location /ibb/api/imageservice {
      set $upstream http://imageservice:8080;
      proxy_pass $upstream;
      rewrite ^/ibb/api/imageservice/v1/(.*)$ /$1 break;
    }
  }
}
